import { Node, Edge } from '@xyflow/react';

// Ansible-tech canvas node `data` payload as read by the playbook generator below.
// Fields come from user-editable, JSON-shaped canvas state (either directly on
// `data`, from legacy nodes, or nested under `data.parameters`), so everything
// is optional. The index signature covers custom-node `{{ var }}` substitution,
// which reads arbitrary keys.
interface AnsibleNodeParams {
  dbUser?: string;
  dbPass?: string;
  port?: string | number;
  startCommand?: string;
  appPort?: string | number;
  packages?: string;
  state?: string;
  username?: string;
  shell?: string;
  createHome?: boolean;
  serviceName?: string;
  enabled?: boolean;
  repoUrl?: string;
  destPath?: string;
  branch?: string;
  buildCommand?: string;
  credentialId?: string;
  appType?: string;
  command?: string;
  chdir?: string;
  srcPath?: string;
  owner?: string;
  mode?: string;
  ansibleUser?: string;
  ansibleHost?: string;
  [key: string]: unknown;
}

interface AnsibleNodeData {
  label?: string;
  isCustom?: boolean;
  tech?: string;
  rawCode?: string;
  parameters?: AnsibleNodeParams;
  // Legacy/flat fields some nodes carry directly on `data` instead of `parameters`
  dbUser?: string;
  dbPass?: string;
  port?: string | number;
  startCommand?: string;
  appPort?: string | number;
  repoUrl?: string;
  branch?: string;
  destPath?: string;
  buildCommand?: string;
  credentialId?: string;
  appType?: string;
  [key: string]: unknown;
}

// Helper function to topologically sort canvas nodes based on connection edges
function getSortedNodes(nodes: Node[], edges: Edge[]): Node[] {
  const nodeMap = new Map<string, Node>();
  nodes.forEach(n => nodeMap.set(n.id, n));

  const adj = new Map<string, string[]>();
  const inDegree = new Map<string, number>();

  nodes.forEach(n => {
    adj.set(n.id, []);
    inDegree.set(n.id, 0);
  });

  edges.forEach(edge => {
    const u = edge.source;
    const v = edge.target;
    if (nodeMap.has(u) && nodeMap.has(v)) {
      adj.get(u)!.push(v);
      inDegree.set(v, inDegree.get(v)! + 1);
    }
  });

  const queue: string[] = [];
  // To keep a stable ordering for unconnected nodes, we iterate in original nodes order
  nodes.forEach(n => {
    if (inDegree.get(n.id) === 0) {
      queue.push(n.id);
    }
  });

  const sortedIds: string[] = [];
  while (queue.length > 0) {
    const u = queue.shift()!;
    sortedIds.push(u);

    const neighbors = adj.get(u) || [];
    neighbors.forEach(v => {
      inDegree.set(v, inDegree.get(v)! - 1);
      if (inDegree.get(v) === 0) {
        queue.push(v);
      }
    });
  }

  // Handle cycles or unvisited nodes by appending them in original order
  if (sortedIds.length < nodes.length) {
    const sortedSet = new Set(sortedIds);
    nodes.forEach(n => {
      if (!sortedSet.has(n.id)) {
        sortedIds.push(n.id);
      }
    });
  }

  return sortedIds.map(id => nodeMap.get(id)!).filter(Boolean);
}

export function generateAnsibleYAML(nodes: Node[], edges: Edge[]): string {
  // If the canvas is empty, return a comment
  if (nodes.length === 0) {
    return '# Your infrastructure canvas is currently empty.\n# Add nodes to generate an Ansible playbook.';
  }

  // Set up the Ansible Playbook boilerplate
  const headerString = `---
# Ansible playbook generated by Whiparc
- name: Automated Infrastructure Provisioning
  hosts: all
  become: yes
  tasks:

    # Configure dpkg to use unsafe IO for massive speedup in containers
    - name: Configure dpkg unsafe IO
      ansible.builtin.shell: |
        mkdir -p /etc/dpkg/dpkg.cfg.d
        echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/force-unsafe-io
      when: ansible_os_family == 'Debian'
      ignore_errors: yes

    # Clean up any stuck apt/dpkg locks if active
    - name: Clean up apt locks
      ansible.builtin.shell: |
        killall -9 apt apt-get dpkg 2>/dev/null || true
        rm -f /var/lib/dpkg/lock-frontend
        rm -f /var/lib/dpkg/lock
        rm -f /var/lib/apt/lists/lock
      when: ansible_os_family == 'Debian'
      ignore_errors: yes

    # Check for interrupted dpkg state
    - name: Check for interrupted dpkg state
      ansible.builtin.shell: dpkg -l | grep -E '^i[^i]'
      register: dpkg_check
      when: ansible_os_family == 'Debian'
      failed_when: false
      changed_when: false

    # Fix interrupted dpkg states only when needed
    - name: Fix interrupted dpkg states
      ansible.builtin.shell: dpkg --configure -a
      when: ansible_os_family == 'Debian' and (dpkg_check.rc is defined and dpkg_check.rc == 0)
      ignore_errors: yes

\n`;

  let tasksString = '';

  // Sort nodes topologically using the connections (edges)
  const sortedNodes = getSortedNodes(nodes, edges);

  sortedNodes.forEach((node) => {
    if (!node || !node.data) {
      return;
    }

    const data = node.data as unknown as AnsibleNodeData;
    const label = data.label || '';
    const id = node.id;
    const p: AnsibleNodeParams = data.parameters || {};

    // Map each visual node to its corresponding Ansible YAML block
    if (id.startsWith('update-packages') || label.includes('Update Packages')) {
      tasksString += `    # Update cache and upgrade packages
    - name: Update apt cache and upgrade packages (Debian)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == 'Debian'

    - name: Update yum cache and upgrade packages (RedHat)
      ansible.builtin.yum:
        update_cache: yes
        name: "*"
        state: latest
      when: ansible_os_family == 'RedHat'\n\n`;
    } 
    else if (id.startsWith('nginx') || label.includes('Install Nginx')) {
      tasksString += `    # Install Nginx Web Server
    - name: Install Nginx Web Server
      ansible.builtin.package:
        name: nginx
        state: present\n\n`;
    } 
    else if (id.startsWith('nodejs') || label.includes('Install Node.js')) {
      tasksString += `    # Install xz dependency
    - name: Install xz-utils (Debian)
      ansible.builtin.package:
        name: xz-utils
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install xz (RedHat)
      ansible.builtin.package:
        name: xz
        state: present
      when: ansible_os_family == 'RedHat'

    # Download Node.js precompiled package
    - name: Download Node.js precompiled package
      ansible.builtin.get_url:
        url: https://nodejs.org/dist/v18.16.0/node-v18.16.0-linux-x64.tar.xz
        dest: /tmp/node-v18.16.0-linux-x64.tar.xz

    # Extract Node.tar.xz to /usr/local
    - name: Extract Node.tar.xz to /usr/local
      ansible.builtin.unarchive:
        src: /tmp/node-v18.16.0-linux-x64.tar.xz
        dest: /usr/local
        remote_src: yes
        extra_opts:
          - --strip-components=1\n\n`;
    }
    else if (id.startsWith('postgresql') || label.includes('Postgres') || label.includes('PostgreSQL')) {
      tasksString += `    # Install PostgreSQL and psycopg2
    - name: Install PostgreSQL and python3-psycopg2 (Debian)
      ansible.builtin.apt:
        name:
          - postgresql
          - python3-psycopg2
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install PostgreSQL and python3-psycopg2 (RedHat)
      ansible.builtin.dnf:
        name:
          - postgresql-server
          - python3-psycopg2
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Initialize PostgreSQL database (RedHat)
      ansible.builtin.command: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION
      when: ansible_os_family == 'RedHat'
      ignore_errors: yes

    - name: Ensure PostgreSQL is running and enabled
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: yes\n\n`;

      const dbUser = data.dbUser || p.dbUser || '{{ db_user }}';
      const dbPass = data.dbPass || p.dbPass || '{{ db_pass }}';
      tasksString += `    # Create PostgreSQL User
    - name: Create PostgreSQL user
      community.postgresql.postgresql_user:
        name: "${dbUser}"
        password: "${dbPass}"
        state: present\n\n`;
    }
    else if (id.startsWith('open-port') || label.includes('Open Port')) {
      const port = data.port || p.port || '{{ port_number }}';
      tasksString += `    # Ensure firewall package is installed
    - name: Install UFW (Debian)
      ansible.builtin.package:
        name: ufw
        state: present
      when: ansible_os_family == 'Debian'

    # Open Port ${port} in UFW
    - name: Open Port ${port} in UFW (Debian)
      ansible.builtin.ufw:
        rule: allow
        port: "${port}"
        proto: tcp
      when: ansible_os_family == 'Debian'
      ignore_errors: yes

    - name: Install firewalld (RedHat)
      ansible.builtin.package:
        name: firewalld
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure firewalld is running (RedHat)
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_os_family == 'RedHat'

    # Open Port ${port} in firewalld
    - name: Open Port ${port} in firewalld (RedHat)
      ansible.builtin.firewalld:
        port: "${port}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_os_family == 'RedHat'
      ignore_errors: yes\n\n`;
    }
    else if (id.startsWith('deploy-node-app') || label.includes('Deploy Node App')) {
      const startCommand = data.startCommand || p.startCommand || 'npm start';
      const appPort = data.appPort || p.appPort || '3000';
      const appName = 'app';

      tasksString += `    # Deploy Node.js Application
    - name: Copy application source code to server
      ansible.builtin.copy:
        src: __APP_SRC_DIR__/
        dest: /home/ubuntu/${appName}
        owner: ubuntu

    # Check if package.json exists in target directory
    - name: Check if package.json exists
      ansible.builtin.stat:
        path: /home/ubuntu/${appName}/package.json
      register: pkg_json

    # Install npm dependencies if package.json exists
    - name: Install npm dependencies
      ansible.builtin.command:
        cmd: npm install
        chdir: /home/ubuntu/${appName}
      when: pkg_json.stat.exists

    # Install pm2 process manager if package.json exists
    - name: Install pm2 process manager
      ansible.builtin.command:
        cmd: npm install -g pm2
      when: pkg_json.stat.exists

    # Start the application with pm2 if package.json exists
    - name: Start the application with pm2
      ansible.builtin.shell: pm2 delete ${appName} >/dev/null 2>&1 || true; PORT=${appPort} pm2 start "${startCommand}" --name ${appName}
      args:
        chdir: /home/ubuntu/${appName}
      when: pkg_json.stat.exists\n\n`;
    }
    else if (id.startsWith('copy-env') || label.includes('Copy .env')) {
      tasksString += `    # Copy .env file to server
    - name: Copy .env file to server
      ansible.builtin.copy:
        src: .env
        dest: /home/ubuntu/.env
        owner: ubuntu
        group: ubuntu
        mode: '0600'\n\n`;
    }
    else if (id.startsWith('apt_install')) {
      const packagesStr = p.packages || 'curl, git, jq';
      const state = p.state || 'present';
      const packagesList = packagesStr.split(',').map((item: string) => `          - ${item.trim()}`).join('\n');
      
      tasksString += `    # Install system packages
    - name: Install specified system packages
      ansible.builtin.package:
        name:
\n${packagesList}
        state: ${state}\n\n`;
    }
    else if (id.startsWith('create_user')) {
      const username = p.username || 'deployer';
      const shell = p.shell || '/bin/bash';
      const createHome = p.createHome !== false ? 'yes' : 'no';

      tasksString += `    # Create system user
    - name: Create system user ${username}
      ansible.builtin.user:
        name: "${username}"
        shell: "${shell}"
        create_home: ${createHome}\n\n`;
    }
    else if (id.startsWith('systemd_service')) {
      const serviceName = p.serviceName || 'nginx';
      const state = p.state || 'started';
      const enabled = p.enabled !== false ? 'yes' : 'no';

      tasksString += `    # Manage Systemd service
    - name: Manage service ${serviceName}
      ansible.builtin.systemd:
        name: "${serviceName}"
        state: "${state}"
        enabled: ${enabled}\n\n`;
    }
    else if (id.startsWith('git_clone')) {
      const repoUrl = p.repoUrl || data.repoUrl || '';
      const destPath = p.destPath || data.destPath || '/var/www/app';
      const branch = p.branch || data.branch || 'main';
      const credentialId = p.credentialId || data.credentialId || '';

      let gitRepoUrl = repoUrl;
      if (credentialId && repoUrl.startsWith('https://')) {
        const cleanUrl = repoUrl.substring(8);
        gitRepoUrl = `https://{{ lookup('env', 'GITHUB_PAT') | default('') }}@${cleanUrl}`;
      }

      tasksString += `    # Git Clone Repository
    - name: Ensure git is installed on target host
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes
      ignore_errors: yes

    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "${destPath}"
        state: directory
        owner: ubuntu
        mode: '0755'

    - name: Clone codebase from git repository
      ansible.builtin.git:
        repo: "${gitRepoUrl}"
        dest: "${destPath}"
        version: "${branch}"
        clone: yes
        update: yes
        force: yes
      ignore_errors: yes\n\n`;
    }
    else if (id.startsWith('shell_command')) {
      const command = p.command || 'echo "hello"';
      const chdir = p.chdir || '/tmp';

      tasksString += `    # Run shell command
    - name: Run arbitrary CLI shell command
      ansible.builtin.shell:
        cmd: "${command}"
        chdir: "${chdir}"\n\n`;
    }
    else if (id.startsWith('file_copy')) {
      const srcPath = p.srcPath || '';
      const destPath = p.destPath || '';
      const owner = p.owner || 'www-data';
      const mode = p.mode || '0644';

      tasksString += `    # Copy custom file
    - name: Copy local file to target path
      ansible.builtin.copy:
        src: "${srcPath}"
        dest: "${destPath}"
        owner: "${owner}"
        mode: "${mode}"\n\n`;
    }
    else if (data.isCustom && data.tech === 'Ansible') {
      const customTasks = data.rawCode || '';
      const lines = customTasks.split('\n').map((line: string) => {
        if (line.trim() === '') return '';
        return '    ' + line;
      }).join('\n');
      
      tasksString += `    # Custom block: ${data.label}\n${lines}\n\n`;
    }
  });

  let fullYaml = headerString + tasksString;
  // Find all unique variables using Regex
  const variableRegex = /{{\s*([\w_]+)\s*}}/g;
  const foundVariables = new Set<string>();
  let match;

  while ((match = variableRegex.exec(fullYaml)) !== null) {
    foundVariables.add(match[1]); // match[1] is the inner text without the brackets
  }

  // If variables were found, inject a 'vars:' block right before 'tasks:'
  if (foundVariables.size > 0) {
    let varsBlock = `  vars:\n`;
    foundVariables.forEach((v) => {
      varsBlock += `    ${v}: "REPLACE_ME_OR_USE_VAULT"\n`;
    });
    
    // Inject the vars block into the final string
    fullYaml = fullYaml.replace('  tasks:\n', `${varsBlock}\n  tasks:\n`);
  }

  return fullYaml;
}