import { describe, expect, it } from "vitest";
import { generateAnsibleYAML } from "../exportYaml";
import { edge, installNginx, updatePackages } from "./fixtures";

const NGINX_TASK = "- name: Install Nginx Web Server";
const UPDATE_TASK = "- name: Update apt cache and upgrade packages (Debian)";

describe("generateAnsibleYAML", () => {
  it("returns an explanatory comment for an empty canvas", () => {
    const yaml = generateAnsibleYAML([], []);
    expect(yaml).toMatch(/^# Your infrastructure canvas is currently empty\./);
    expect(yaml).not.toContain("hosts:");
  });

  it("emits a playbook header attributed to Whiparc", () => {
    const yaml = generateAnsibleYAML([updatePackages()], []);
    expect(yaml).toContain("# Ansible playbook generated by Whiparc");
    expect(yaml).toContain("hosts: all");
    expect(yaml).toContain("become: yes");
  });

  it("maps node types to their Ansible tasks", () => {
    const yaml = generateAnsibleYAML([updatePackages(), installNginx()], []);
    expect(yaml).toContain(UPDATE_TASK);
    expect(yaml).toContain(NGINX_TASK);
  });

  it("keeps canvas order for unconnected nodes", () => {
    const yaml = generateAnsibleYAML([updatePackages(), installNginx()], []);
    expect(yaml.indexOf(UPDATE_TASK)).toBeLessThan(yaml.indexOf(NGINX_TASK));
  });

  it("orders tasks topologically by edges, not by canvas order", () => {
    // Canvas order is update -> nginx, but the edge says nginx runs first.
    const nodes = [updatePackages(), installNginx()];
    const yaml = generateAnsibleYAML(nodes, [edge("nginx-1", "update-packages-1")]);
    expect(yaml.indexOf(NGINX_TASK)).toBeLessThan(yaml.indexOf(UPDATE_TASK));
  });

  it("ignores edges that point at nodes which do not exist", () => {
    const nodes = [updatePackages(), installNginx()];
    const yaml = generateAnsibleYAML(nodes, [edge("ghost", "nginx-1"), edge("nginx-1", "ghost")]);
    expect(yaml).toContain(UPDATE_TASK);
    expect(yaml).toContain(NGINX_TASK);
  });

  it("still emits every node when the graph contains a cycle", () => {
    const nodes = [updatePackages(), installNginx()];
    const yaml = generateAnsibleYAML(nodes, [
      edge("update-packages-1", "nginx-1"),
      edge("nginx-1", "update-packages-1"),
    ]);
    expect(yaml).toContain(UPDATE_TASK);
    expect(yaml).toContain(NGINX_TASK);
  });
});
