FROM ghcr.io/whiparc/whiparc-sandbox-base:latest

# Copy the public key for passwordless authentication
COPY id_rsa.pub /home/ubuntu/.ssh/authorized_keys
RUN chmod 600 /home/ubuntu/.ssh/authorized_keys && chown -R ubuntu:root /home/ubuntu/.ssh

# Run SSH daemon in foreground
CMD ["/usr/sbin/sshd", "-D"]
